.TH "qwtlicense" 3 "Mon Jun 13 2016" "Version 6.1.3" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qwtlicense \- Qwt License, Version 1\&.0 

.PP
.nf
1                              Qwt License
2                            Version 1\&.0, January 1, 2003
3 
4 The Qwt library and included programs are provided under the terms
5 of the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) with the following
6 exceptions:
7 
8     1\&. Widgets that are subclassed from Qwt widgets do not
9        constitute a derivative work\&.
10 
11     2\&. Static linking of applications and widgets to the
12        Qwt library does not constitute a derivative work
13        and does not require the author to provide source
14        code for the application or widget, use the shared
15        Qwt libraries, or link their applications or
16        widgets against a user-supplied version of Qwt\&.
17 
18        If you link the application or widget to a modified
19        version of Qwt, then the changes to Qwt must be 
20        provided under the terms of the LGPL in sections
21        1, 2, and 4\&.
22 
23     3\&. You do not have to provide a copy of the Qwt license
24        with programs that are linked to the Qwt library, nor
25        do you have to identify the Qwt license in your
26        program or documentation as required by section 6
27        of the LGPL\&.
28 
29 
30        However, programs must still identify their use of Qwt\&.
31        The following example statement can be included in user
32        documentation to satisfy this requirement:
33 
34            [program/widget] is based in part on the work of
35            the Qwt project (http://qwt\&.sf\&.net)\&.
36 
37 ----------------------------------------------------------------------
38 
39 
40           GNU LESSER GENERAL PUBLIC LICENSE
41                Version 2\&.1, February 1999
42 
43  Copyright (C) 1991, 1999 Free Software Foundation, Inc\&.
44      59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
45  Everyone is permitted to copy and distribute verbatim copies
46  of this license document, but changing it is not allowed\&.
47 
48 [This is the first released version of the Lesser GPL\&.  It also counts
49  as the successor of the GNU Library Public License, version 2, hence
50  the version number 2\&.1\&.]
51 
52                 Preamble
53 
54   The licenses for most software are designed to take away your
55 freedom to share and change it\&.  By contrast, the GNU General Public
56 Licenses are intended to guarantee your freedom to share and change
57 free software--to make sure the software is free for all its users\&.
58 
59   This license, the Lesser General Public License, applies to some
60 specially designated software packages--typically libraries--of the
61 Free Software Foundation and other authors who decide to use it\&.  You
62 can use it too, but we suggest you first think carefully about whether
63 this license or the ordinary General Public License is the better
64 strategy to use in any particular case, based on the explanations below\&.
65 
66   When we speak of free software, we are referring to freedom of use,
67 not price\&.  Our General Public Licenses are designed to make sure that
68 you have the freedom to distribute copies of free software (and charge
69 for this service if you wish); that you receive source code or can get
70 it if you want it; that you can change the software and use pieces of
71 it in new free programs; and that you are informed that you can do
72 these things\&.
73 
74   To protect your rights, we need to make restrictions that forbid
75 distributors to deny you these rights or to ask you to surrender these
76 rights\&.  These restrictions translate to certain responsibilities for
77 you if you distribute copies of the library or if you modify it\&.
78 
79   For example, if you distribute copies of the library, whether gratis
80 or for a fee, you must give the recipients all the rights that we gave
81 you\&.  You must make sure that they, too, receive or can get the source
82 code\&.  If you link other code with the library, you must provide
83 complete object files to the recipients, so that they can relink them
84 with the library after making changes to the library and recompiling
85 it\&.  And you must show them these terms so they know their rights\&.
86 
87   We protect your rights with a two-step method: (1) we copyright the
88 library, and (2) we offer you this license, which gives you legal
89 permission to copy, distribute and/or modify the library\&.
90 
91   To protect each distributor, we want to make it very clear that
92 there is no warranty for the free library\&.  Also, if the library is
93 modified by someone else and passed on, the recipients should know
94 that what they have is not the original version, so that the original
95 author's reputation will not be affected by problems that might be
96 introduced by others\&.
97 
98   Finally, software patents pose a constant threat to the existence of
99 any free program\&.  We wish to make sure that a company cannot
100 effectively restrict the users of a free program by obtaining a
101 restrictive license from a patent holder\&.  Therefore, we insist that
102 any patent license obtained for a version of the library must be
103 consistent with the full freedom of use specified in this license\&.
104 
105   Most GNU software, including some libraries, is covered by the
106 ordinary GNU General Public License\&.  This license, the GNU Lesser
107 General Public License, applies to certain designated libraries, and
108 is quite different from the ordinary General Public License\&.  We use
109 this license for certain libraries in order to permit linking those
110 libraries into non-free programs\&.
111 
112   When a program is linked with a library, whether statically or using
113 a shared library, the combination of the two is legally speaking a
114 combined work, a derivative of the original library\&.  The ordinary
115 General Public License therefore permits such linking only if the
116 entire combination fits its criteria of freedom\&.  The Lesser General
117 Public License permits more lax criteria for linking other code with
118 the library\&.
119 
120   We call this license the "Lesser" General Public License because it
121 does Less to protect the user's freedom than the ordinary General
122 Public License\&.  It also provides other free software developers Less
123 of an advantage over competing non-free programs\&.  These disadvantages
124 are the reason we use the ordinary General Public License for many
125 libraries\&.  However, the Lesser license provides advantages in certain
126 special circumstances\&.
127 
128   For example, on rare occasions, there may be a special need to
129 encourage the widest possible use of a certain library, so that it becomes
130 a de-facto standard\&.  To achieve this, non-free programs must be
131 allowed to use the library\&.  A more frequent case is that a free
132 library does the same job as widely used non-free libraries\&.  In this
133 case, there is little to gain by limiting the free library to free
134 software only, so we use the Lesser General Public License\&.
135 
136   In other cases, permission to use a particular library in non-free
137 programs enables a greater number of people to use a large body of
138 free software\&.  For example, permission to use the GNU C Library in
139 non-free programs enables many more people to use the whole GNU
140 operating system, as well as its variant, the GNU/Linux operating
141 system\&.
142 
143   Although the Lesser General Public License is Less protective of the
144 users' freedom, it does ensure that the user of a program that is
145 linked with the Library has the freedom and the wherewithal to run
146 that program using a modified version of the Library\&.
147 
148   The precise terms and conditions for copying, distribution and
149 modification follow\&.  Pay close attention to the difference between a
150 "work based on the library" and a "work that uses the library"\&.  The
151 former contains code derived from the library, whereas the latter must
152 be combined with the library in order to run\&.
153 
154           GNU LESSER GENERAL PUBLIC LICENSE
155    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
156 
157   0\&. This License Agreement applies to any software library or other
158 program which contains a notice placed by the copyright holder or
159 other authorized party saying it may be distributed under the terms of
160 this Lesser General Public License (also called "this License")\&.
161 Each licensee is addressed as "you"\&.
162 
163   A "library" means a collection of software functions and/or data
164 prepared so as to be conveniently linked with application programs
165 (which use some of those functions and data) to form executables\&.
166 
167   The "Library", below, refers to any such software library or work
168 which has been distributed under these terms\&.  A "work based on the
169 Library" means either the Library or any derivative work under
170 copyright law: that is to say, a work containing the Library or a
171 portion of it, either verbatim or with modifications and/or translated
172 straightforwardly into another language\&.  (Hereinafter, translation is
173 included without limitation in the term "modification"\&.)
174 
175   "Source code" for a work means the preferred form of the work for
176 making modifications to it\&.  For a library, complete source code means
177 all the source code for all modules it contains, plus any associated
178 interface definition files, plus the scripts used to control compilation
179 and installation of the library\&.
180 
181   Activities other than copying, distribution and modification are not
182 covered by this License; they are outside its scope\&.  The act of
183 running a program using the Library is not restricted, and output from
184 such a program is covered only if its contents constitute a work based
185 on the Library (independent of the use of the Library in a tool for
186 writing it)\&.  Whether that is true depends on what the Library does
187 and what the program that uses the Library does\&.
188 
189   1\&. You may copy and distribute verbatim copies of the Library's
190 complete source code as you receive it, in any medium, provided that
191 you conspicuously and appropriately publish on each copy an
192 appropriate copyright notice and disclaimer of warranty; keep intact
193 all the notices that refer to this License and to the absence of any
194 warranty; and distribute a copy of this License along with the
195 Library\&.
196 
197   You may charge a fee for the physical act of transferring a copy,
198 and you may at your option offer warranty protection in exchange for a
199 fee\&.
200 
201   2\&. You may modify your copy or copies of the Library or any portion
202 of it, thus forming a work based on the Library, and copy and
203 distribute such modifications or work under the terms of Section 1
204 above, provided that you also meet all of these conditions:
205 
206     a) The modified work must itself be a software library\&.
207 
208     b) You must cause the files modified to carry prominent notices
209     stating that you changed the files and the date of any change\&.
210 
211     c) You must cause the whole of the work to be licensed at no
212     charge to all third parties under the terms of this License\&.
213 
214     d) If a facility in the modified Library refers to a function or a
215     table of data to be supplied by an application program that uses
216     the facility, other than as an argument passed when the facility
217     is invoked, then you must make a good faith effort to ensure that,
218     in the event an application does not supply such function or
219     table, the facility still operates, and performs whatever part of
220     its purpose remains meaningful\&.
221 
222     (For example, a function in a library to compute square roots has
223     a purpose that is entirely well-defined independent of the
224     application\&.  Therefore, Subsection 2d requires that any
225     application-supplied function or table used by this function must
226     be optional: if the application does not supply it, the square
227     root function must still compute square roots\&.)
228 
229 These requirements apply to the modified work as a whole\&.  If
230 identifiable sections of that work are not derived from the Library,
231 and can be reasonably considered independent and separate works in
232 themselves, then this License, and its terms, do not apply to those
233 sections when you distribute them as separate works\&.  But when you
234 distribute the same sections as part of a whole which is a work based
235 on the Library, the distribution of the whole must be on the terms of
236 this License, whose permissions for other licensees extend to the
237 entire whole, and thus to each and every part regardless of who wrote
238 it\&.
239 
240 Thus, it is not the intent of this section to claim rights or contest
241 your rights to work written entirely by you; rather, the intent is to
242 exercise the right to control the distribution of derivative or
243 collective works based on the Library\&.
244 
245 In addition, mere aggregation of another work not based on the Library
246 with the Library (or with a work based on the Library) on a volume of
247 a storage or distribution medium does not bring the other work under
248 the scope of this License\&.
249 
250   3\&. You may opt to apply the terms of the ordinary GNU General Public
251 License instead of this License to a given copy of the Library\&.  To do
252 this, you must alter all the notices that refer to this License, so
253 that they refer to the ordinary GNU General Public License, version 2,
254 instead of to this License\&.  (If a newer version than version 2 of the
255 ordinary GNU General Public License has appeared, then you can specify
256 that version instead if you wish\&.)  Do not make any other change in
257 these notices\&.
258 
259   Once this change is made in a given copy, it is irreversible for
260 that copy, so the ordinary GNU General Public License applies to all
261 subsequent copies and derivative works made from that copy\&.
262 
263   This option is useful when you wish to copy part of the code of
264 the Library into a program that is not a library\&.
265 
266   4\&. You may copy and distribute the Library (or a portion or
267 derivative of it, under Section 2) in object code or executable form
268 under the terms of Sections 1 and 2 above provided that you accompany
269 it with the complete corresponding machine-readable source code, which
270 must be distributed under the terms of Sections 1 and 2 above on a
271 medium customarily used for software interchange\&.
272 
273   If distribution of object code is made by offering access to copy
274 from a designated place, then offering equivalent access to copy the
275 source code from the same place satisfies the requirement to
276 distribute the source code, even though third parties are not
277 compelled to copy the source along with the object code\&.
278 
279   5\&. A program that contains no derivative of any portion of the
280 Library, but is designed to work with the Library by being compiled or
281 linked with it, is called a "work that uses the Library"\&.  Such a
282 work, in isolation, is not a derivative work of the Library, and
283 therefore falls outside the scope of this License\&.
284 
285   However, linking a "work that uses the Library" with the Library
286 creates an executable that is a derivative of the Library (because it
287 contains portions of the Library), rather than a "work that uses the
288 library"\&.  The executable is therefore covered by this License\&.
289 Section 6 states terms for distribution of such executables\&.
290 
291   When a "work that uses the Library" uses material from a header file
292 that is part of the Library, the object code for the work may be a
293 derivative work of the Library even though the source code is not\&.
294 Whether this is true is especially significant if the work can be
295 linked without the Library, or if the work is itself a library\&.  The
296 threshold for this to be true is not precisely defined by law\&.
297 
298   If such an object file uses only numerical parameters, data
299 structure layouts and accessors, and small macros and small inline
300 functions (ten lines or less in length), then the use of the object
301 file is unrestricted, regardless of whether it is legally a derivative
302 work\&.  (Executables containing this object code plus portions of the
303 Library will still fall under Section 6\&.)
304 
305   Otherwise, if the work is a derivative of the Library, you may
306 distribute the object code for the work under the terms of Section 6\&.
307 Any executables containing that work also fall under Section 6,
308 whether or not they are linked directly with the Library itself\&.
309 
310   6\&. As an exception to the Sections above, you may also combine or
311 link a "work that uses the Library" with the Library to produce a
312 work containing portions of the Library, and distribute that work
313 under terms of your choice, provided that the terms permit
314 modification of the work for the customer's own use and reverse
315 engineering for debugging such modifications\&.
316 
317   You must give prominent notice with each copy of the work that the
318 Library is used in it and that the Library and its use are covered by
319 this License\&.  You must supply a copy of this License\&.  If the work
320 during execution displays copyright notices, you must include the
321 copyright notice for the Library among them, as well as a reference
322 directing the user to the copy of this License\&.  Also, you must do one
323 of these things:
324 
325     a) Accompany the work with the complete corresponding
326     machine-readable source code for the Library including whatever
327     changes were used in the work (which must be distributed under
328     Sections 1 and 2 above); and, if the work is an executable linked
329     with the Library, with the complete machine-readable "work that
330     uses the Library", as object code and/or source code, so that the
331     user can modify the Library and then relink to produce a modified
332     executable containing the modified Library\&.  (It is understood
333     that the user who changes the contents of definitions files in the
334     Library will not necessarily be able to recompile the application
335     to use the modified definitions\&.)
336 
337     b) Use a suitable shared library mechanism for linking with the
338     Library\&.  A suitable mechanism is one that (1) uses at run time a
339     copy of the library already present on the user's computer system,
340     rather than copying library functions into the executable, and (2)
341     will operate properly with a modified version of the library, if
342     the user installs one, as long as the modified version is
343     interface-compatible with the version that the work was made with\&.
344 
345     c) Accompany the work with a written offer, valid for at
346     least three years, to give the same user the materials
347     specified in Subsection 6a, above, for a charge no more
348     than the cost of performing this distribution\&.
349 
350     d) If distribution of the work is made by offering access to copy
351     from a designated place, offer equivalent access to copy the above
352     specified materials from the same place\&.
353 
354     e) Verify that the user has already received a copy of these
355     materials or that you have already sent this user a copy\&.
356 
357   For an executable, the required form of the "work that uses the
358 Library" must include any data and utility programs needed for
359 reproducing the executable from it\&.  However, as a special exception,
360 the materials to be distributed need not include anything that is
361 normally distributed (in either source or binary form) with the major
362 components (compiler, kernel, and so on) of the operating system on
363 which the executable runs, unless that component itself accompanies
364 the executable\&.
365 
366   It may happen that this requirement contradicts the license
367 restrictions of other proprietary libraries that do not normally
368 accompany the operating system\&.  Such a contradiction means you cannot
369 use both them and the Library together in an executable that you
370 distribute\&.
371 
372   7\&. You may place library facilities that are a work based on the
373 Library side-by-side in a single library together with other library
374 facilities not covered by this License, and distribute such a combined
375 library, provided that the separate distribution of the work based on
376 the Library and of the other library facilities is otherwise
377 permitted, and provided that you do these two things:
378 
379     a) Accompany the combined library with a copy of the same work
380     based on the Library, uncombined with any other library
381     facilities\&.  This must be distributed under the terms of the
382     Sections above\&.
383 
384     b) Give prominent notice with the combined library of the fact
385     that part of it is a work based on the Library, and explaining
386     where to find the accompanying uncombined form of the same work\&.
387 
388   8\&. You may not copy, modify, sublicense, link with, or distribute
389 the Library except as expressly provided under this License\&.  Any
390 attempt otherwise to copy, modify, sublicense, link with, or
391 distribute the Library is void, and will automatically terminate your
392 rights under this License\&.  However, parties who have received copies,
393 or rights, from you under this License will not have their licenses
394 terminated so long as such parties remain in full compliance\&.
395 
396   9\&. You are not required to accept this License, since you have not
397 signed it\&.  However, nothing else grants you permission to modify or
398 distribute the Library or its derivative works\&.  These actions are
399 prohibited by law if you do not accept this License\&.  Therefore, by
400 modifying or distributing the Library (or any work based on the
401 Library), you indicate your acceptance of this License to do so, and
402 all its terms and conditions for copying, distributing or modifying
403 the Library or works based on it\&.
404 
405   10\&. Each time you redistribute the Library (or any work based on the
406 Library), the recipient automatically receives a license from the
407 original licensor to copy, distribute, link with or modify the Library
408 subject to these terms and conditions\&.  You may not impose any further
409 restrictions on the recipients' exercise of the rights granted herein\&.
410 You are not responsible for enforcing compliance by third parties with
411 this License\&.
412 
413   11\&. If, as a consequence of a court judgment or allegation of patent
414 infringement or for any other reason (not limited to patent issues),
415 conditions are imposed on you (whether by court order, agreement or
416 otherwise) that contradict the conditions of this License, they do not
417 excuse you from the conditions of this License\&.  If you cannot
418 distribute so as to satisfy simultaneously your obligations under this
419 License and any other pertinent obligations, then as a consequence you
420 may not distribute the Library at all\&.  For example, if a patent
421 license would not permit royalty-free redistribution of the Library by
422 all those who receive copies directly or indirectly through you, then
423 the only way you could satisfy both it and this License would be to
424 refrain entirely from distribution of the Library\&.
425 
426 If any portion of this section is held invalid or unenforceable under any
427 particular circumstance, the balance of the section is intended to apply,
428 and the section as a whole is intended to apply in other circumstances\&.
429 
430 It is not the purpose of this section to induce you to infringe any
431 patents or other property right claims or to contest validity of any
432 such claims; this section has the sole purpose of protecting the
433 integrity of the free software distribution system which is
434 implemented by public license practices\&.  Many people have made
435 generous contributions to the wide range of software distributed
436 through that system in reliance on consistent application of that
437 system; it is up to the author/donor to decide if he or she is willing
438 to distribute software through any other system and a licensee cannot
439 impose that choice\&.
440 
441 This section is intended to make thoroughly clear what is believed to
442 be a consequence of the rest of this License\&.
443 
444   12\&. If the distribution and/or use of the Library is restricted in
445 certain countries either by patents or by copyrighted interfaces, the
446 original copyright holder who places the Library under this License may add
447 an explicit geographical distribution limitation excluding those countries,
448 so that distribution is permitted only in or among countries not thus
449 excluded\&.  In such case, this License incorporates the limitation as if
450 written in the body of this License\&.
451 
452   13\&. The Free Software Foundation may publish revised and/or new
453 versions of the Lesser General Public License from time to time\&.
454 Such new versions will be similar in spirit to the present version,
455 but may differ in detail to address new problems or concerns\&.
456 
457 Each version is given a distinguishing version number\&.  If the Library
458 specifies a version number of this License which applies to it and
459 "any later version", you have the option of following the terms and
460 conditions either of that version or of any later version published by
461 the Free Software Foundation\&.  If the Library does not specify a
462 license version number, you may choose any version ever published by
463 the Free Software Foundation\&.
464 
465   14\&. If you wish to incorporate parts of the Library into other free
466 programs whose distribution conditions are incompatible with these,
467 write to the author to ask for permission\&.  For software which is
468 copyrighted by the Free Software Foundation, write to the Free
469 Software Foundation; we sometimes make exceptions for this\&.  Our
470 decision will be guided by the two goals of preserving the free status
471 of all derivatives of our free software and of promoting the sharing
472 and reuse of software generally\&.
473 
474                 NO WARRANTY
475 
476   15\&. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO
477 WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW\&.
478 EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR
479 OTHER PARTIES PROVIDE THE LIBRARY "AS IS" WITHOUT WARRANTY OF ANY
480 KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
481 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
482 PURPOSE\&.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
483 LIBRARY IS WITH YOU\&.  SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME
484 THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION\&.
485 
486   16\&. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN
487 WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY
488 AND/OR REDISTRIBUTE THE LIBRARY AS PERMITTED ABOVE, BE LIABLE TO YOU
489 FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR
490 CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
491 LIBRARY (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
492 RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
493 FAILURE OF THE LIBRARY TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
494 SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
495 DAMAGES\&.
496 
497              END OF TERMS AND CONDITIONS
498 
499            How to Apply These Terms to Your New Libraries
500 
501   If you develop a new library, and you want it to be of the greatest
502 possible use to the public, we recommend making it free software that
503 everyone can redistribute and change\&.  You can do so by permitting
504 redistribution under these terms (or, alternatively, under the terms of the
505 ordinary General Public License)\&.
506 
507   To apply these terms, attach the following notices to the library\&.  It is
508 safest to attach them to the start of each source file to most effectively
509 convey the exclusion of warranty; and each file should have at least the
510 "copyright" line and a pointer to where the full notice is found\&.
511 
512     <one line to give the library's name and a brief idea of what it does\&.>
513     Copyright (C) <year>  <name of author>
514 
515     This library is free software; you can redistribute it and/or
516     modify it under the terms of the GNU Lesser General Public
517     License as published by the Free Software Foundation; either
518     version 2\&.1 of the License, or (at your option) any later version\&.
519 
520     This library is distributed in the hope that it will be useful,
521     but WITHOUT ANY WARRANTY; without even the implied warranty of
522     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.  See the GNU
523     Lesser General Public License for more details\&.
524 
525     You should have received a copy of the GNU Lesser General Public
526     License along with this library; if not, write to the Free Software
527     Foundation, Inc\&., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
528 
529 Also add information on how to contact you by electronic and paper mail\&.
530 
531 You should also get your employer (if you work as a programmer) or your
532 school, if any, to sign a "copyright disclaimer" for the library, if
533 necessary\&.  Here is a sample; alter the names:
534 
535   Yoyodyne, Inc\&., hereby disclaims all copyright interest in the
536   library `Frob' (a library for tweaking knobs) written by James Random Hacker\&.
537 
538   <signature of Ty Coon>, 1 April 1990
539   Ty Coon, President of Vice
540 
541 That's all there is to it!
542 
543 

.fi
.PP
 
